---

# Docker role variable
# ---------------------
docker_daemon_options:
  exec-opts:
    - "native.cgroupdriver=systemd"
  log-driver: "json-file"
  log-opts:
    max-size: "100m"
  data-root: "/var/docker/lib"
docker_users:
  - ubuntu