---
global:
  checkNewVersion: false
  sendAnonymousUsage: false

# Logging
log:
  level: "INFO"
  filePath: "/var/log/traefik/traefik.log"
accessLog:
  filePath: "/var/log/traefik/access.log"

ping:
  entryPoint: ping

# Entry Points
entryPoints:
  ping:
    address: :8082
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
    proxyProtocol:
      trustedIPs:
        - "10.0.0.0/16"
    forwardedHeaders:
      trustedIPs:
        - "10.0.0.0/16"
  websecure:
    address: ":443"
    proxyProtocol:
      trustedIPs:
        - "10.0.0.0/16"
    forwardedHeaders:
      trustedIPs:
        - "10.0.0.0/16"

# Certificate resolvers
certificatesResolvers:
  ionos:
    acme:
      email: admin@ricsanfre.com
      storage: acme.json
      dnsChallenge:
        provider: ionos
        resolvers: 
          - 1.1.1.1:53
          - 8.8.8.8:53

# Providers
providers:
  # Swarm provider to discover services in the docker swarm
  swarm:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: frontend
  file:
    directory: /etc/traefik/files
    watch: true
