---
- name: Enable HTTPS incoming traffic
  hosts: oci
  become: true
  gather_facts: false

  tasks:
    - name: Allow incoming HTTPS traffic
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 443
        jump: ACCEPT
        match: state
        ctstate: NEW
        comment: "Allow incoming HTTPS traffic"
        # state: absent

    - name: Save current state of the firewall in system file
      community.general.iptables_state:
        ip_version: ipv4
        table: filter
        state: saved
        path: /etc/iptables/rules.v4