[project]
name = "oci-provisioning-ansible"
version = "0.1.0"
description = "Applying configuration changes to OCI infrastructure"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ansible>=12.2.0",
]
