services:
  whoami:
    image: traefik/whoami:v1.11.0
    hostname: whoami
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == oci-amd-2
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.swarm.network=frontend
        - traefik.http.services.whoami.loadbalancer.server.port=80
        - traefik.http.routers.whoami-http.rule=Host(`whoamiwhoami.test.ricsanfre.com`)
        - traefik.http.routers.whoami-http.entrypoints=web
        - traefik.http.routers.whoami-https.rule=Host(`whoami.test.ricsanfre.com`)
        - traefik.http.routers.whoami-https.entrypoints=websecure
        - traefik.http.routers.whoami-https.tls=true
        - traefik.http.routers.whoami-https.tls.certresolver=ionos
    networks:
      - frontend

networks:
  frontend:
    external: true